---
title: Stackbit Fjord Theme
baseurl: "/"
permalink: "/:title/"
palette: yellow
header:
  title: Pioneer Engineering LLC
  tagline: Alaska Well and Septic Testing
  logo_img: "/images/Logo-1.png"
  bg_img: "/images/wellhead pic.jpg"
  has_nav: true
  has_social: true
footer:
  content: "&copy; All rights reserved."
  links:
  - text: Made with Stackbit
    url: https://www.stackbit.com
    new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
- jekyll-menus
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ssg-build.sh
- LICENSE.md
- README.md
- netlify.toml
- stackbit-build.sh
- stackbit-pull.js
collections:
  posts:
    permalink: "/posts/:title/"
